export const REGISTRAR_USUARIO = 'REGISTRAR_USUARIO'
export const REGISTRAR_USUARIO_EXITO = 'REGISTRAR_USUARIO_EXITO'
export const REGISTRAR_USUARIO_ERROR = 'REGISTRAR_USUARIO_ERROR'

export const LOGIN_USUARIO = 'LOGIN_USUARIO'
export const LOGIN_USUARIO_EXITO = 'LOGIN_USUARIO_EXITO'
export const LOGIN_USUARIO_ERROR = 'LOGIN_USUARIO_ERROR'

export const CONFIRMAR_USUARIO = 'CONFIRMAR_USUARIO'
export const CONFIRMAR_USUARIO_EXITO = 'CONFIRMAR_USUARIO_EXITO'
export const CONFIRMAR_USUARIO_ERROR = 'CONFIRMAR_USUARIO_ERROR'

export const RESETEAR_MENSAJE = 'RESETEAR_MENSAJE'

export const CAMBIAR_PASSWORD = 'CAMBIAR_PASSWORD'
export const CAMBIAR_PASSWORD_EXITO = 'CAMBIAR_PASSWORD_EXITO'
export const CAMBIAR_PASSWORD_ERROR = 'CAMBIAR_PASSWORD_ERROR'