export const REGISTRAR_USUARIO = 'REGISTRAR_USUARIO'
export const REGISTRAR_USUARIO_EXITO = 'REGISTRAR_USUARIO_EXITO'
export const REGISTRAR_USUARIO_ERROR = 'REGISTRAR_USUARIO_ERROR'

export const LOGIN_USUARIO = 'LOGIN_USUARIO'
export const LOGIN_USUARIO_EXITO = 'LOGIN_USUARIO_EXITO'
export const LOGIN_USUARIO_ERROR = 'LOGIN_USUARIO_ERROR'

export const CONFIRMAR_USUARIO = 'CONFIRMAR_USUARIO'
export const CONFIRMAR_USUARIO_EXITO = 'CONFIRMAR_USUARIO_EXITO'
export const CONFIRMAR_USUARIO_ERROR = 'CONFIRMAR_USUARIO_ERROR'

export const RESETEAR_MENSAJE = 'RESETEAR_MENSAJE'

export const CAMBIAR_PASSWORD = 'CAMBIAR_PASSWORD'
export const CAMBIAR_PASSWORD_EXITO = 'CAMBIAR_PASSWORD_EXITO'
export const CAMBIAR_PASSWORD_ERROR = 'CAMBIAR_PASSWORD_ERROR'

export const RECOVERY_PASSWORD = 'RECOVERY_PASSWORD'
export const RECOVERY_PASSWORD_EXITO = 'RECOVERY_PASSWORD_EXITO'
export const RECOVERY_PASSWORD_ERROR = 'RECOVERY_PASSWORD_ERROR'

export const OBTENER_PERFIL = 'OBTENER_PERFIL'
export const OBTENER_PERFIL_EXITO = 'OBTENER_PERFIL_EXITO'
export const OBTENER_PERFIL_ERROR = 'OBTENER_PERFIL_ERROR'

export const NUEVO_USUARIO_DATOS = 'NUEVO_USUARIO_DATOS'
export const NUEVO_USUARIO_DATOS_EXITO = 'NUEVO_USUARIO_DATOS_EXITO'
export const NUEVO_USUARIO_DATOS_ERROR = 'NUEVO_USUARIO_DATOS_ERROR'


// Types Empresa

export const ACTUALIZAR_DATOS_EMPRESA = 'ACTUALIZAR_DATOS_EMPRESA'
export const ACTUALIZAR_DATOS_EMPRESA_EXITO = 'ACTUALIZAR_DATOS_EMPRESA_EXITO'
export const ACTUALIZAR_DATOS_EMPRESA_ERROR = 'ACTUALIZAR_DATOS_EMPRESA_ERROR'

export const OBTENER_DATOS_EMPRESA = 'OBTENER_DATOS_EMPRESA'
export const OBTENER_DATOS_EMPRESA_EXITO = 'OBTENER_DATOS_EMPRESA_EXITO'
export const OBTENER_DATOS_EMPRESA_ERROR = 'OBTENER_DATOS_EMPRESA_ERROR'

// Departamentos

export const OBTENER_DEPARTAMENTOS_EMPRESA = 'OBTENER_DEPARTAMENTOS_EMPRESA'
export const OBTENER_DEPARTAMENTOS_EMPRESA_EXITO = 'OBTENER_DEPARTAMENTOS_EMPRESA_EXITO'
export const OBTENER_DEPARTAMENTOS_EMPRESA_ERROR = 'OBTENER_DEPARTAMENTOS_EMPRESA_ERROR'

export const CREAR_DEPARTAMENTO = 'CREAR_DEPARTAMENTO'
export const CREAR_DEPARTAMENTO_EXITO = 'CREAR_DEPARTAMENTO_EXITO'
export const CREAR_DEPARTAMENTO_ERROR = 'CREAR_DEPARTAMENTO_ERROR'

export const MODIFICAR_DEPARTAMENTO = 'MODIFICAR_DEPARTAMENTO'
export const MODIFICAR_DEPARTAMENTO_EXITO = 'MODIFICAR_DEPARTAMENTO_EXITO'
export const MODIFICAR_DEPARTAMENTO_ERROR = 'MODIFICAR_DEPARTAMENTO_ERROR'

export const ELIMINAR_DEPARTAMENTO = 'ELIMINAR_DEPARTAMENTO'
export const ELIMINAR_DEPARTAMENTO_EXITO = 'ELIMINAR_DEPARTAMENTO_EXITO'
export const ELIMINAR_DEPARTAMENTO_ERROR = 'ELIMINAR_DEPARTAMENTO_ERROR'

// Categorias

export const CREAR_CATEGORIA_DEPARTAMENTO = 'CREAR_CATEGORIA_DEPARTAMENTO'
export const CREAR_CATEGORIA_DEPARTAMENTO_EXITO = 'CREAR_CATEGORIA_DEPARTAMENTO_EXITO'
export const CREAR_CATEGORIA_DEPARTAMENTO_ERROR = 'CREAR_CATEGORIA_DEPARTAMENTO_ERROR'

export const OBTENER_CATEGORIAS_DEPARTAMENTO = 'OBTENER_CATEGORIAS_DEPARTAMENTO'
export const OBTENER_CATEGORIAS_DEPARTAMENTO_EXITO = 'OBTENER_CATEGORIAS_DEPARTAMENTO_EXITO'
export const OBTENER_CATEGORIAS_DEPARTAMENTO_ERROR = 'OBTENER_CATEGORIAS_DEPARTAMENTO_ERROR'

export const ELIMINAR_CATEGORIA_DEPARTAMENTO = 'ELIMINAR_CATEGORIA_DEPARTAMENTO'
export const ELIMINAR_CATEGORIA_DEPARTAMENTO_EXITO = 'ELIMINAR_CATEGORIA_DEPARTAMENTO_EXITO'
export const ELIMINAR_CATEGORIA_DEPARTAMENTO_ERROR = 'ELIMINAR_CATEGORIA_DEPARTAMENTO_ERROR'

// Plazas

export const AGREGAR_PLAZA = 'AGREGAR_PLAZA'
export const AGREGAR_PLAZA_EXITO = 'AGREGAR_PLAZA_EXITO'
export const AGREGAR_PLAZA_ERROR = 'AGREGAR_PLAZA_ERROR'

export const OBTENER_PLAZAS = 'OBTENER_PLAZAS'
export const OBTENER_PLAZAS_EXITO = 'OBTENER_PLAZAS_EXITO'
export const OBTENER_PLAZAS_ERROR = 'OBTENER_PLAZAS_ERROR'

export const GET_PLAZA_BY_ID = 'GET_PLAZA_BY_ID'
export const GET_PLAZA_BY_ID_EXITO = 'GET_PLAZA_BY_ID_EXITO'
export const GET_PLAZA_BY_ID_ERROR = 'GET_PLAZA_BY_ID_ERROR'

export const ELIMINAR_PLAZA = 'ELIMINAR_PLAZA'
export const ELIMINAR_PLAZA_EXITO = 'ELIMINAR_PLAZA_EXITO'
export const ELIMINAR_PLAZA_ERROR = 'ELIMINAR_PLAZA_ERROR'

// CHECKS EMPRESA
export const GET_CHECKS_ADMIN = 'GET_CHECKS_ADMIN'
export const GET_CHECKS_ADMIN_EXITO = "GET_CHECKS_ADMIN_EXITO"
export const GET_CHECKS_ADMIN_ERROR = "GET_CHECKS_ADMIN_ERROR"

// Nominas

export const GENERAR_NOMINA = 'GENERAR_NOMINA'
export const GENERAR_NOMINA_EXITO = 'GENERAR_NOMINA_EXITO'
export const GENERAR_NOMINA_ERROR = 'GENERAR_NOMINA_ERROR'

export const OBTENER_NOMINAS_EMPRESA = 'OBTENER_NOMINAS_EMPRESA'
export const OBTENER_NOMINAS_EMPRESA_EXITO = 'OBTENER_NOMINAS_EMPRESA_EXITO'
export const OBTENER_NOMINAS_EMPRESA_ERROR = 'OBTENER_NOMINAS_EMPRESA_ERROR'

export const ELIMINAR_NOMINA_EMPLEADO = 'ELIMINAR_NOMINA_EMPLEADO'
export const ELIMINAR_NOMINA_EMPLEADO_EXITO = 'ELIMINAR_NOMINA_EMPLEADO_EXITO'
export const ELIMINAR_NOMINA_EMPLEADO_ERROR = 'ELIMINAR_NOMINA_EMPLEADO_ERROR'

//empleados

export const GET_SOLICITUDES = 'GET_SOLICITUDES'
export const GET_SOLICITUDES_EXITO = 'GET_SOLICITUDES_EXITO'
export const GET_SOLICITUDES_ERROR = 'GET_SOLICITUDES_ERROR'

export const RECHAZAR_SOLICITUD = 'RECHAZAR_SOLICITUD'
export const RECHAZAR_SOLICITUD_EXITO = 'RECHAZAR_SOLICITUD_EXITO'
export const RECHAZAR_SOLICITUD_ERROR = 'RECHAZAR_SOLICITUD_ERROR'

export const ACEPTAR_SOLICITUD = 'ACEPTAR_SOLICITUD'
export const ACEPTAR_SOLICITUD_EXITO = 'ACEPTAR_SOLICITUD_EXITO'
export const ACEPTAR_SOLICITUD_ERROR = 'ACEPTAR_SOLICITUD_ERROR'

export const OBTENER_EMPLEADOS = 'OBTENER_EMPLEADOS'
export const OBTENER_EMPLEADOS_EXITO = 'OBTENER_EMPLEADOS_EXITO'
export const OBTENER_EMPLEADOS_ERROR = 'OBTENER_EMPLEADOS_ERROR'

export const OBTENER_EMPLEADOS_EN_PLAZA = 'OBTENER_EMPLEADOS_EN_PLAZA'
export const OBTENER_EMPLEADOS_EN_PLAZA_EXITO = 'OBTENER_EMPLEADOS_EN_PLAZA_EXITO'
export const OBTENER_EMPLEADOS_EN_PLAZA_ERROR = 'OBTENER_EMPLEADOS_EN_PLAZA_ERROR'

export const EDITAR_PLAZA = 'EDITAR_PLAZA'
export const EDITAR_PLAZA_EXITO = 'EDITAR_PLAZA_EXITO'
export const EDITAR_PLAZA_ERROR = 'EDITAR_PLAZA_ERROR'

export const GET_EMPLEADO = 'GET_EMPLEADO'
export const GET_EMPLEADO_EXITO = 'GET_EMPLEADO_EXITO'
export const GET_EMPLEADO_ERROR = 'GET_EMPLEADO_ERROR'

export const REGISTRAR_ENTRADA = 'REGISTRAR_ENTRADA'
export const REGISTRAR_ENTRADA_EXITO = 'REGISTRAR_ENTRADA_EXITO'
export const REGISTRAR_ENTRADA_ERROR = 'REGISTRAR_ENTRADA_ERROR'

export const REGISTRAR_SALIDA = "REGISTRAR_SALIDA"
export const REGISTRAR_SALIDA_EXITO = "REGISTRAR_SALIDA_EXITO"
export const REGISTRAR_SALIDA_ERROR = "REGISTRAR_SALIDA_ERROR"

// helper

export const SET_ID_CATEGORIA = 'SET_ID_CATEGORIA'
export const SET_ID_DEPARTAMENTO = 'SET_ID_DEPARTAMENTO'
export const SET_ID_EMPRESA = 'SET_ID_EMPRESA'


// Types Empleado
export const BUSCAR_PLAZA_USER = 'BUSCAR_PLAZA_USER'
export const BUSCAR_PLAZA_USER_EXITO = 'BUSCAR_PLAZA_USER_EXITO'
export const BUSCAR_PLAZA_USER_ERROR = 'BUSCAR_PLAZA_USER_ERROR'

export const ACCEDER_EMPRESA = 'ACCEDER_EMPRESA'
export const ACCEDER_EMPRESA_EXITO = 'ACCEDER_EMPRESA_EXITO'
export const ACCEDER_EMPRESA_ERROR = 'ACCEDER_EMPRESA_ERROR'

export const EMPLEADO_LOGIN = 'EMPLEADO_LOGIN'
export const EMPLEADO_LOGIN_EXITO = 'EMPLEADO_LOGIN_EXITO'
export const EMPLEADO_LOGIN_ERROR = 'EMPLEADO_LOGIN_ERROR'