export const REGISTRAR_USUARIO = 'REGISTRAR_USUARIO'
export const REGISTRAR_USUARIO_EXITO = 'REGISTRAR_USUARIO_EXITO'
export const REGISTRAR_USUARIO_ERROR = 'REGISTRAR_USUARIO_ERROR'

export const LOGIN_USUARIO = 'LOGIN_USUARIO'
export const LOGIN_USUARIO_EXITO = 'LOGIN_USUARIO_EXITO'
export const LOGIN_USUARIO_ERROR = 'LOGIN_USUARIO_ERROR'

export const CONFIRMAR_USUARIO = 'CONFIRMAR_USUARIO'
export const CONFIRMAR_USUARIO_EXITO = 'CONFIRMAR_USUARIO_EXITO'
export const CONFIRMAR_USUARIO_ERROR = 'CONFIRMAR_USUARIO_ERROR'

export const RESETEAR_MENSAJE = 'RESETEAR_MENSAJE'

export const CAMBIAR_PASSWORD = 'CAMBIAR_PASSWORD'
export const CAMBIAR_PASSWORD_EXITO = 'CAMBIAR_PASSWORD_EXITO'
export const CAMBIAR_PASSWORD_ERROR = 'CAMBIAR_PASSWORD_ERROR'

export const RECOVERY_PASSWORD = 'RECOVERY_PASSWORD'
export const RECOVERY_PASSWORD_EXITO = 'RECOVERY_PASSWORD_EXITO'
export const RECOVERY_PASSWORD_ERROR = 'RECOVERY_PASSWORD_ERROR'

export const OBTENER_PERFIL = 'OBTENER_PERFIL'
export const OBTENER_PERFIL_EXITO = 'OBTENER_PERFIL_EXITO'
export const OBTENER_PERFIL_ERROR = 'OBTENER_PERFIL_ERROR'

export const NUEVO_USUARIO_DATOS = 'NUEVO_USUARIO_DATOS'
export const NUEVO_USUARIO_DATOS_EXITO = 'NUEVO_USUARIO_DATOS_EXITO'
export const NUEVO_USUARIO_DATOS_ERROR = 'NUEVO_USUARIO_DATOS_ERROR'


// Types Empresa

export const ACTUALIZAR_DATOS_EMPRESA = 'ACTUALIZAR_DATOS_EMPRESA'
export const ACTUALIZAR_DATOS_EMPRESA_EXITO = 'ACTUALIZAR_DATOS_EMPRESA_EXITO'
export const ACTUALIZAR_DATOS_EMPRESA_ERROR = 'ACTUALIZAR_DATOS_EMPRESA_ERROR'

export const OBTENER_DATOS_EMPRESA = 'OBTENER_DATOS_EMPRESA'
export const OBTENER_DATOS_EMPRESA_EXITO = 'OBTENER_DATOS_EMPRESA_EXITO'
export const OBTENER_DATOS_EMPRESA_ERROR = 'OBTENER_DATOS_EMPRESA_ERROR'

// Departamentos

export const OBTENER_DEPARTAMENTOS_EMPRESA = 'OBTENER_DEPARTAMENTOS_EMPRESA'
export const OBTENER_DEPARTAMENTOS_EMPRESA_EXITO = 'OBTENER_DEPARTAMENTOS_EMPRESA_EXITO'
export const OBTENER_DEPARTAMENTOS_EMPRESA_ERROR = 'OBTENER_DEPARTAMENTOS_EMPRESA_ERROR'

export const CREAR_DEPARTAMENTO = 'CREAR_DEPARTAMENTO'
export const CREAR_DEPARTAMENTO_EXITO = 'CREAR_DEPARTAMENTO_EXITO'
export const CREAR_DEPARTAMENTO_ERROR = 'CREAR_DEPARTAMENTO_ERROR'

export const MODIFICAR_DEPARTAMENTO = 'MODIFICAR_DEPARTAMENTO'
export const MODIFICAR_DEPARTAMENTO_EXITO = 'MODIFICAR_DEPARTAMENTO_EXITO'
export const MODIFICAR_DEPARTAMENTO_ERROR = 'MODIFICAR_DEPARTAMENTO_ERROR'

export const ELIMINAR_DEPARTAMENTO = 'ELIMINAR_DEPARTAMENTO'
export const ELIMINAR_DEPARTAMENTO_EXITO = 'ELIMINAR_DEPARTAMENTO_EXITO'
export const ELIMINAR_DEPARTAMENTO_ERROR = 'ELIMINAR_DEPARTAMENTO_ERROR'

// Categorias

export const CREAR_CATEGORIA_DEPARTAMENTO = 'CREAR_CATEGORIA_DEPARTAMENTO'
export const CREAR_CATEGORIA_DEPARTAMENTO_EXITO = 'CREAR_CATEGORIA_DEPARTAMENTO_EXITO'
export const CREAR_CATEGORIA_DEPARTAMENTO_ERROR = 'CREAR_CATEGORIA_DEPARTAMENTO_ERROR'

export const OBTENER_CATEGORIAS_DEPARTAMENTO = 'OBTENER_CATEGORIAS_DEPARTAMENTO'
export const OBTENER_CATEGORIAS_DEPARTAMENTO_EXITO = 'OBTENER_CATEGORIAS_DEPARTAMENTO_EXITO'
export const OBTENER_CATEGORIAS_DEPARTAMENTO_ERROR = 'OBTENER_CATEGORIAS_DEPARTAMENTO_ERROR'

export const ELIMINAR_CATEGORIA_DEPARTAMENTO = 'ELIMINAR_CATEGORIA_DEPARTAMENTO'
export const ELIMINAR_CATEGORIA_DEPARTAMENTO_EXITO = 'ELIMINAR_CATEGORIA_DEPARTAMENTO_EXITO'
export const ELIMINAR_CATEGORIA_DEPARTAMENTO_ERROR = 'ELIMINAR_CATEGORIA_DEPARTAMENTO_ERROR'

// Plazas

export const AGREGAR_PLAZA = 'AGREGAR_PLAZA'
export const AGREGAR_PLAZA_EXITO = 'AGREGAR_PLAZA_EXITO'
export const AGREGAR_PLAZA_ERROR = 'AGREGAR_PLAZA_ERROR'

export const OBTENER_PLAZAS = 'OBTENER_PLAZAS'
export const OBTENER_PLAZAS_EXITO = 'OBTENER_PLAZAS_EXITO'
export const OBTENER_PLAZAS_ERROR = 'OBTENER_PLAZAS_ERROR'

export const GET_PLAZA_BY_ID = 'GET_PLAZA_BY_ID'
export const GET_PLAZA_BY_ID_EXITO = 'GET_PLAZA_BY_ID_EXITO'
export const GET_PLAZA_BY_ID_ERROR = 'GET_PLAZA_BY_ID_ERROR'

// helper

export const SET_ID_CATEGORIA = 'SET_ID_CATEGORIA'
export const SET_ID_DEPARTAMENTO = 'SET_ID_DEPARTAMENTO'
export const SET_ID_EMPRESA = 'SET_ID_EMPRESA'
